services:
    app.contact:
        class: AppBundle\Service\ContactService
        arguments: [ '@mailer' ]

    app.registration:
        class: AppBundle\User\RegistrationService
        arguments:
            - '@security.secure_random'
            - '@security.password_encoder'
            - '@doctrine.orm.entity_manager'

    app.game_runner:
        class: AppBundle\Game\GameRunner
        arguments: [ '@app.game_context', '@?app.word_list', '%dictionaries%' ]

    app.game_context:
        class: AppBundle\Game\GameContext
        arguments: [ '@session' ]
        public: false

    app.word_list:
        class: AppBundle\Game\WordList
        #lazy: true
        public: false
        calls:
            - [ addLoader, [ txt, '@app.text_file_loader' ] ]
            - [ addLoader, [ xml, '@app.xml_file_loader' ] ]
            #- [ loadDictionaries, [ '%dictionaries%' ] ]

    app.text_file_loader:
        class: AppBundle\Game\Loader\TextFileLoader
        public: false

    app.xml_file_loader:
        class: AppBundle\Game\Loader\XmlFileLoader
        public: false
