services:
    app.super_admin_voter:
        class: AppBundle\Security\SuperAdminVoter
        public: false
        tags:
            - { name: security.voter, priority: -1000 }

    app.view_profile_voter:
        class: AppBundle\Security\ViewProfileVoter
        public: false
        tags:
            - { name: security.voter }

    app.credits_balance_debitor:
        class: AppBundle\User\CreditsBalanceDebitor
        arguments: [ '@security.token_storage', '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_subscriber }

    app.language_detector:
        class: AppBundle\Http\AcceptLanguageDetector
        tags:
            - { name: kernel.event_subscriber }

    app.contact:
        class: AppBundle\Service\ContactService
        arguments: [ '@mailer' ]

    app.registration:
        class: AppBundle\User\RegistrationService
        arguments:
            - '@security.secure_random'
            - '@security.password_encoder'
            - '@doctrine.orm.entity_manager'

    app.game_runner:
        class: AppBundle\Game\GameRunner
        arguments:
            - '@app.game_context'
            - '@?event_dispatcher'
            - '@?app.word_list'
            - '%dictionaries%'

    app.game_context:
        class: AppBundle\Game\GameContext
        arguments: [ '@session' ]
        public: false

    app.word_list:
        class: AppBundle\Game\WordList
        #lazy: true
        public: false
#        calls:
#            - [ addLoader, [ txt, '@app.text_file_loader' ] ]
#            - [ addLoader, [ xml, '@app.xml_file_loader' ] ]
#            - [ loadDictionaries, [ '%dictionaries%' ] ]

    app.text_file_loader:
        class: AppBundle\Game\Loader\TextFileLoader
        public: false
        tags:
            - { name: hangman.dictionary_loader, type: txt }

    app.xml_file_loader:
        class: AppBundle\Game\Loader\XmlFileLoader
        public: false
        tags:
            - { name: hangman.dictionary_loader, type: xml }
